# Generated by Django 3.2 on 2021-04-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legs',
            name='legs_color',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_feature',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_gender',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_language',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_neuter',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_sleep_time',
        ),
        migrations.RemoveField(
            model_name='legs',
            name='legs_talent',
        ),
        migrations.AddField(
            model_name='legs',
            name='legs_sub1_type',
            field=models.CharField(default='한국땅', max_length=100, verbose_name='서브1 분류'),
        ),
        migrations.AddField(
            model_name='legs',
            name='legs_sub2_type',
            field=models.CharField(default='길에서 태어난', max_length=100, verbose_name='서브2 분류'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='멤버컬러'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_feature',
            field=models.TextField(blank=True, max_length=5000, verbose_name='특색'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_language',
            field=models.CharField(blank=True, max_length=10, verbose_name='사용하는 언어'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_neuter',
            field=models.BooleanField(default=False, verbose_name='중성화여부'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_sleep_time',
            field=models.FloatField(default=18.5, verbose_name='수면시간'),
        ),
        migrations.AddField(
            model_name='members',
            name='member_talent',
            field=models.TextField(blank=True, max_length=5000, verbose_name='뛰어난 재능'),
        ),
        migrations.AlterField(
            model_name='legs',
            name='legs_type',
            field=models.CharField(choices=[('people', '휴먼'), ('cat', '애옹쓰'), ('dog', '멍뭉이'), ('another', '?!?!')], default='people', max_length=10, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='멤버소개'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_legs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.legs', verbose_name='종족'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='종족'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_regular',
            field=models.BooleanField(default=False, verbose_name='정규 멤버 여부'),
        ),
    ]
