# Generated by Django 3.2 on 2021-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210429_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legs',
            options={'ordering': ('-pk',), 'verbose_name': '종족', 'verbose_name_plural': '종족 목록'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ('-pk',), 'verbose_name': '구성원', 'verbose_name_plural': '구성원 목록'},
        ),
        migrations.AlterField(
            model_name='legs',
            name='legs_sub2_type',
            field=models.CharField(default='대구병원', max_length=100, verbose_name='서브2 분류'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='고유 색깔'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_language',
            field=models.CharField(blank=True, max_length=1000, verbose_name='사용하는 언어'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_regular',
            field=models.BooleanField(default=False, verbose_name='정규 구성원 여부'),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_talent',
            field=models.TextField(blank=True, max_length=5000, verbose_name='재능 소개'),
        ),
    ]
